### PR TITLE
add binder badge and link

### PR DESCRIPTION
**Pull request by kmader**
adding binder badge and use-case binder link

### CODE REVIEW

**Comment by janfreyberg** [comment]
Awesome, thank you! Will this automatically install the package and dependencies on binder?

**Comment by kmader** [comment]
it pip installs the package itself per default, but for the example.ipynb I guess we want to have the ipyevents and bs4 to really show it off?

**Comment by janfreyberg** [comment]
Yes, that would be useful. Can you specify additional dependencies only for binder? (It's been a long time since I used it)

**Comment by kmader** [comment]
Yea you make a binder folder, you can try the version pre-merging using this link: https://mybinder.org/v2/gh/kmader/superintendent/patch-1?filepath=examples.ipynb

**Comment by janfreyberg** [comment]
Works great! thanks!

**Pull request merged**
